# Generated by Django 2.2 on 2020-06-15 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayPhoto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
